version: '3.7'

services:
  nginx:
    build: ./requirements/nginx
    image: nginx:mine
    container_name: nginx

    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - vol_wp:/data/www/html
    env_file:
      - .env

    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:mine

    networks:
      - inception
    volumes:
      - vol_wp:/data/www/html
    env_file:
      - .env
    
    depends_on:
      - mariadb
    restart: always

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:mine
    container_name: mariadb

    networks:
      - inception
    volumes:
      - vol_mariadb:/var/lib/mysql
    env_file:
      - .env

    restart: always

volumes:
  vol_wp:
    driver_opts:
      type: none
      o: bind
      device: /home/chsimon/data/wordpress
  vol_mariadb:
    driver_opts:
      type: none
      o: bind
      device: /home/chsimon/data/mariadb

networks:
  inception:
    name:   inception
    driver: bridge